### ISSUE TITLE
This CTranslate2 package was not compiled with CUDA support

### ISSUE THREAD

**Issue by taloglu** [fictions-ai/autocaption#3]
I get the following error when I run the Streamlit application.

```This CTranslate2 package was not compiled with CUDA support```

Would you know what I should do to fix it? Do I need a GPU to run the model? I am using a Macbook Pro M1.

**Comment by taloglu** [comment]
My mistake

Change line 363 to ```model = WhisperModel(model_size, device="cpu")``` instead of cuda and float16.

**Comment by FurkanGozukara** [comment]
@taloglu have you tested how much time it takes? showing me 5 hours for 7 min video : https://github.com/fictions-ai/autocaption/issues/4
